apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyal-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eyal-project
  template:
    metadata:
      labels:
        app: eyal-project
    spec:
      containers:
      - name: eyal-project
        image: eyal:tag3
        ports:
        - containerPort: 9000
        env:
        - name: REDIS_HOST
          value: eyal-redis-server
        - name: REDIS_PORT
          value: "6379"
        volumeMounts:
        - name: source-volume
          mountPath: /sources  # Mount PVC at the correct path
      volumes:
      - name: source-volume
        persistentVolumeClaim:
          claimName: eyal-pvc
