apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eyal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Request the same size as the PV's capacity
